version: "3.3"

services:
  kong:
    image: kong:alpine
    volumes:
      - ./kong.yml:/tmp/kong.yml
      - ./kong/plugins/magalu-tdc:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-magalu-tdc/1.0.0-1/lua/kong/plugins/magalu-tdc
      - ./kong/plugins/magalu-tdc:/usr/local/share/lua/5.1/kong/plugins/magalu-tdc
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled,magalu-tdc
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
