name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Integration
      run: |
        git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
        KONG_VERSION=2.3.2 ../kong-pongo/pongo.sh build
        ../kong-pongo/pongo.sh run ./spec/integration

    - name: Unit
      run: |
        make cov
